### ISSUE TITLE
Q: Producing multiple tasks

### ISSUE THREAD

**Issue by phretor** [CERT-Polska/karton#171]
I'm posting this question here because there's no GitHub Discussion tab.

Is it allowed to spawn multiple tasks in sequence from within the same producer? I noticed that all my tasks never complete if I do the following:

```python
...
        tag_task = Task(
            {
                "type": "sample",
                "stage": "analyzed",
                "kind": "runnable",
            },
            payload={
                "sample": sample,
                "parent": sample,
                "tags": tags,
            },
        )
        self.send_task(tag_task)

        blob_task = Task(
            {"type": "blob", "kind": "my-custom-json"},
            payload={
                "parent": sample,
                "content": my_stuff,
            },
        )
        self.send_task(blob_task)
...
```

So I'm wondering if this is an acceptable pattern or I'm violating some assumptions that I'm not aware of.

**Comment by psrok1** [comment]
Issues are a good place for posting such questions, especially because they sometimes turn out to be an issue.

And yes, submitting plenty of tasks is definitely acceptable and we're doing it as well in our internal services.

> I noticed that all my tasks never complete if I do the following:

So that sounds like a bug. Could you post more code to explain the context? Maybe there is some issue.
